# Generated by Django 5.2.7 on 2025-12-15 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sistema_proyecto', '0001_initial'),
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('vibracion', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibracion', models.FloatField(default=0)),
                ('temperatura', models.FloatField(blank=True, default=0, null=True)),
                ('humedad', models.FloatField(blank=True, default=0, null=True)),
                ('voltaje', models.FloatField(default=0)),
                ('corriente', models.FloatField(default=0)),
                ('potencia', models.FloatField(default=0)),
                ('energia', models.FloatField(default=0)),
                ('costo', models.FloatField(default=0)),
                ('factor_potencia', models.FloatField(default=1)),
                ('frecuencia', models.FloatField(default=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ssid', models.CharField(blank=True, max_length=100, null=True)),
                ('bssid', models.CharField(blank=True, max_length=100, null=True)),
                ('herramienta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sistema_proyecto.herramienta')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='sensor.sensor')),
            ],
            options={
                'db_table': 'Sistema_proyecto_medicion',
            },
        ),
    ]
