# Generated by Django 5.2.7 on 2026-05-04 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_proyecto', '0004_alter_cotizacion_servicio'),
        ('mediciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sistema_proyecto.ordentrabajo'),
        ),
    ]
