# Generated by Django 5.2.7 on 2026-05-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0002_medicion_orden_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='costo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
