# Generated by Django 5.2.7 on 2025-12-15 21:14

import Sistema_proyecto.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('vibracion', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.BooleanField(default=False)),
                ('tipo_alerta', models.CharField(blank=True, max_length=50, null=True)),
                ('detalle_alerta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='cotizaciones_archivos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_entrega', models.DateField(validators=[Sistema_proyecto.models.validate_delivery_date])),
            ],
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En uso'), ('en_reposo', 'En reposo')], default='disponible', max_length=20)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temperatura', 'Temperatura Alta'), ('vibracion', 'Vibración Elevada'), ('corriente', 'Sobrecorriente'), ('horario', 'Uso Fuera de Horario')], max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('vibracion', models.FloatField(blank=True, null=True)),
                ('corriente', models.FloatField(blank=True, null=True)),
                ('visto', models.BooleanField(default=False)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_proyecto.herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('accion', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_rfid', to='Sistema_proyecto.herramienta')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_rfid', to='sensor.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden_compra', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=200)),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='ordenes_compra_archivos/')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_proyecto.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ot', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.CharField(max_length=200)),
                ('tecnico', models.CharField(blank=True, max_length=200, null=True)),
                ('servicio', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada'), ('entregada', 'Entregada')], default='pendiente', max_length=20)),
                ('energia_total_kwh', models.FloatField(default=0)),
                ('costo_energia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('temp_promedio', models.FloatField(default=0)),
                ('humedad_promedio', models.FloatField(default=0)),
                ('vibracion_max', models.FloatField(default=0)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='ordenes_trabajo_archivos/')),
                ('herramientas', models.ManyToManyField(blank=True, to='Sistema_proyecto.herramienta')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sistema_proyecto.ordencompra')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_energia', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('archivo_cotizacion', models.FileField(blank=True, null=True, upload_to='facturas/cotizacion/')),
                ('archivo_presupuesto', models.FileField(blank=True, null=True, upload_to='facturas/presupuesto/')),
                ('archivo_oc', models.FileField(blank=True, null=True, upload_to='facturas/oc/')),
                ('archivo_ot', models.FileField(blank=True, null=True, upload_to='facturas/ot/')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema_proyecto.ordencompra')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema_proyecto.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=200)),
                ('servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('monto_base', models.FloatField(default=0)),
                ('monto_estimado', models.DecimalField(decimal_places=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='presupuestos_archivos/')),
                ('costo_energia', models.FloatField(default=0)),
                ('energia_total', models.FloatField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_proyecto.cotizacion')),
                ('herramienta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sistema_proyecto.herramienta')),
            ],
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema_proyecto.presupuesto'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema_proyecto.presupuesto'),
        ),
        migrations.CreateModel(
            name='RegistroUsoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('energia_consumida', models.FloatField(default=0)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_proyecto.herramienta')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_proyecto.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(blank=True, db_column='rut', max_length=12, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComentarioOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_proyecto.ordentrabajo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
