# Generated by Django 5.2.7 on 2026-05-03 19:32

import Sistema_proyecto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, validators=[Sistema_proyecto.models.validate_delivery_date]),
        ),
    ]
