# Generated by Django 5.2.7 on 2026-05-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_proyecto', '0002_alter_cotizacion_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='monto_base',
            field=models.IntegerField(default=0),
        ),
    ]
