# Generated by Django 5.2.7 on 2026-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_proyecto', '0003_alter_presupuesto_monto_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='servicio',
            field=models.CharField(choices=[('granallado ecológico PUING 13H₂O', 'Granallado Ecológico PUING 13H₂O'), ('limpieza y recuperación de fachadas', 'Limpieza y Recuperación de Fachadas'), ('procesos metales y preparación', 'Procesos Metales y Preparación'), ('descontaminación post-incendio', 'Descontaminación Post-Incendio'), ('eliminación de rebabas y preparación', 'Eliminación de Rebabas y Preparación')], default='granallado ecológico PUING 13H₂O', max_length=150),
        ),
    ]
