# Generated by Django 5.2.7 on 2026-05-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_proyecto', '0004_alter_cotizacion_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
