# Generated by Django 5.2.7 on 2026-05-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_proyecto', '0005_alter_cotizacion_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='servicio',
            field=models.CharField(choices=[('', 'Seleccionar servicio...'), ('Granallado Ecológico PUING 13H₂O', 'Granallado Ecológico PUING 13H₂O'), ('Limpieza y Recuperación de Fachadas', 'Limpieza y Recuperación de Fachadas'), ('Procesos Metales y Preparación', 'Procesos Metales y Preparación'), ('Descontaminación Post-Incendio', 'Descontaminación Post-Incendio'), ('Eliminación de Rebabas y Preparación', 'Eliminación de Rebabas y Preparación')], default='', max_length=150),
        ),
    ]
