# Generated by Django 5.2.7 on 2026-05-05 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_proyecto', '0006_alter_cotizacion_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='monto_base',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registrousoherramienta',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sistema_proyecto.ordentrabajo'),
        ),
    ]
