# Generated by Django 5.2.7 on 2026-05-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_proyecto', '0007_alter_presupuesto_monto_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('herramientas', models.ManyToManyField(blank=True, to='Sistema_proyecto.herramienta')),
            ],
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sistema_proyecto.trabajador'),
        ),
    ]
